language: minimal
sudo: required
services:
  - docker
install:
  - gem install travis --no-rdoc --no-ri
matrix:
  fast_finish: true
env:
  - TEST_TYPE=bazel.test
script: ./ci/ci_steps.sh

branches:
  only:
    - master
