version: 2
jobs:
   test:
     docker:
       - image: envoyproxy/envoy-build:52f6880ffbf761c9b809fc3ac208900956ff16b4
     resource_class: xlarge
     working_directory: /source
     steps:
       - checkout
       - run: ci/do_ci.sh bazel.test
   docs:
     docker:
       - image: lyft/envoy-build:114e24c6fd05fc026492e9d2ca5608694e5ea59d
     resource_class: xlarge
     working_directory: /source
     steps:
       - checkout
       - run: ci/do_ci.sh bazel.docs
       - add_ssh_keys
       - run: docs/publish.sh
       - store_artifacts:
           path: generated/docs
   format:
     docker:
       - image: lyft/envoy-build:114e24c6fd05fc026492e9d2ca5608694e5ea59d
     resource_class: xlarge
     working_directory: /source
     steps:
       - checkout
       - run: ci/do_ci.sh check_format

workflows:
  version: 2
  all:
    jobs:
      - test
      - docs
      - format
